### ISSUE TITLE
Inkscape?

### ISSUE THREAD

**Issue by RyannDaGreat** [tomdeabreucodes/PyJig#2]
How do I set up my environment to make this code work? Thank you!
```
Traceback (most recent call last):
  File "<rp-input-17>", line 8, in <module>
    myjig.generate_svg_jigsaw("./Pieces")
  File "/opt/homebrew/lib/python3.10/site-packages/pyjigsaw/jigsawfactory.py", line 250, in generate_svg_jigsaw
    bboxes = subprocess.check_output(
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'inkscape'
```

**Comment by tomdeabreucodes** [comment]
PyJig uses the [Inkscape](https://inkscape.org/) CLI to get the bounding boxes for each of the puzzle pieces.

It is a 3rd party programme, and the installation method varies depending on your OS, but there is a guide [here](https://wiki.inkscape.org/wiki/Installing_Inkscape) which covers all bases.

I'll update the README to mention that.
